name: Backend CI

on:
  push:
    branches: ['**']

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js (Backend)
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies (Backend)
        run: npm ci

      - name: Build TypeScript (Backend)
        run: npm run build

      - name: Run tests (Backend)
        run: npm run test:coverage
